apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: DOCKERHUB_USER/flask-demo:0.1.0
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet: { path: /healthz, port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /healthz, port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 20
